### ISSUE TITLE
Fonts don't display when there are  '[', ']', characters in the version string

### ISSUE THREAD

**Issue by MariannaPaszkowska** [TypeNetwork/videoproof#35]
I noticed today that fonts don't display in the tool when there are `[`, `]`, characters in the version string (name table ID=5).
After removing those characters from the version string, the fonts were loading normally.

**Comment by graphicore** [comment]
Thanks. That string ends up in the CSS `font-family` property to select  the font, probably it's not allowed there.

**Comment by graphicore** [comment]
@MariannaPaszkowska I wonder, since I'm trying to replicate the issue, in my simulated case I get an alert box `loadFontsFromFiles:SyntaxError: FontFace.family setter: Invalid font descriptor`

![Screenshot from 2023-01-26 13-49-05](https://user-images.githubusercontent.com/393132/214839651-245eca4f-6e9b-4597-955a-f8317dbad1f3.png)

Do you see this as well?

**Comment by graphicore** [comment]
Fixed with #35 @MariannaPaszkowska please test and re-open if the issue still occurs.

**Comment by MariannaPaszkowska** [comment]
@graphicore Thanks for fixing it! I can confirm that fonts with "[]" chars in name ID 5 are loading now for me.
